# Generated by Django 4.2.2 on 2023-06-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Время начала занятия')),
                ('time_end', models.TimeField(verbose_name='Время окончания занятия')),
                ('mentor_days', models.ManyToManyField(related_name='mentor_days', to='schedule.weekdays', verbose_name='День недели')),
                ('reviewer_days', models.ManyToManyField(related_name='reviewer_days', to='schedule.weekdays', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
