# Generated by Django 4.2.2 on 2023-06-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='course_end_date',
            field=models.DateField(auto_now_add=True, verbose_name='День окончания курса'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course_start_date',
            field=models.DateField(auto_now_add=True, verbose_name='День начала курса'),
        ),
    ]
