# Generated by Django 4.2.2 on 2023-06-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('schedule', '0012_cancelinggroupsclass_alter_schedule_course_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancelinggroupclass',
            options={'verbose_name_plural': 'Отмена занятия у группы'},
        ),
        migrations.AlterModelOptions(
            name='cancelinggroupsclass',
            options={'verbose_name_plural': 'Отмена занятий у групп'},
        ),
        migrations.RemoveField(
            model_name='cancelinggroupclass',
            name='group',
        ),
        migrations.AddField(
            model_name='cancelinggroupclass',
            name='group',
            field=models.ManyToManyField(related_name='cancels', to='users.group', verbose_name='Группа'),
        ),
    ]
